service: serverless-ts-boilerplate
useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  environment:
    SECRET_KEY: ${env:SECRET_KEY}

functions:
  webhook:
    handler: src/handler.webhook
    url:
      cors: false
